# WebDriver.ps1ファイル内のエラーコード参照を新しい体系に更新するスクリプト

Write-Host "=== WebDriverエラーコード更新開始 ===" -ForegroundColor Green

$webDriverFile = "$PSScriptRoot\_lib\WebDriver.ps1"

# エラーコードのマッピング（旧→新）
$errorCodeMapping = @{
    # 初期化・接続関連エラー (1001-1010) - 変更なし
    "INIT_ERROR" = "INIT_ERROR"
    "BROWSER_START_ERROR" = "BROWSER_START_ERROR"
    "TAB_INFO_ERROR" = "TAB_INFO_ERROR"
    "WEBSOCKET_CONNECTION_ERROR" = "WEBSOCKET_CONNECTION_ERROR"
    "WEBSOCKET_SEND_ERROR" = "WEBSOCKET_SEND_ERROR"
    "WEBSOCKET_RECEIVE_ERROR" = "WEBSOCKET_RECEIVE_ERROR"
    "DISPOSE_ERROR" = "DISPOSE_ERROR"
    
    # ナビゲーション関連エラー (1011-1020) - 変更なし
    "NAVIGATION_ERROR" = "NAVIGATION_ERROR"
    "GO_BACK_ERROR" = "GO_BACK_ERROR"
    "GO_FORWARD_ERROR" = "GO_FORWARD_ERROR"
    "REFRESH_ERROR" = "REFRESH_ERROR"
    "WAIT_FOR_PAGE_LOAD_ERROR" = "WAIT_FOR_PAGE_LOAD_ERROR"
    "AD_LOAD_WAIT_ERROR" = "AD_LOAD_WAIT_ERROR"
    
    # 要素検索関連エラー (1021-1040) - 変更なし
    "FIND_ELEMENT_ERROR" = "FIND_ELEMENT_ERROR"
    "FIND_ELEMENT_GENERIC_ERROR" = "FIND_ELEMENT_GENERIC_ERROR"
    "FIND_ELEMENT_XPATH_ERROR" = "FIND_ELEMENT_XPATH_ERROR"
    "FIND_ELEMENT_CLASSNAME_ERROR" = "FIND_ELEMENT_CLASSNAME_ERROR"
    "FIND_ELEMENT_ID_ERROR" = "FIND_ELEMENT_ID_ERROR"
    "FIND_ELEMENT_NAME_ERROR" = "FIND_ELEMENT_NAME_ERROR"
    "FIND_ELEMENT_TAGNAME_ERROR" = "FIND_ELEMENT_TAGNAME_ERROR"
    "FIND_ELEMENTS_ERROR" = "FIND_ELEMENTS_ERROR"
    "FIND_ELEMENTS_GENERIC_ERROR" = "FIND_ELEMENTS_GENERIC_ERROR"
    "FIND_ELEMENTS_BY_CLASSNAME_ERROR" = "FIND_ELEMENTS_BY_CLASSNAME_ERROR"
    "FIND_ELEMENTS_BY_NAME_ERROR" = "FIND_ELEMENTS_BY_NAME_ERROR"
    "FIND_ELEMENTS_BY_TAGNAME_ERROR" = "FIND_ELEMENTS_BY_TAGNAME_ERROR"
    "IS_EXISTS_ELEMENT_GENERIC_ERROR" = "IS_EXISTS_ELEMENT_GENERIC_ERROR"
    "IS_EXISTS_ELEMENT_XPATH_ERROR" = "IS_EXISTS_ELEMENT_XPATH_ERROR"
    "IS_EXISTS_ELEMENT_CLASSNAME_ERROR" = "IS_EXISTS_ELEMENT_CLASSNAME_ERROR"
    "IS_EXISTS_ELEMENT_ID_ERROR" = "IS_EXISTS_ELEMENT_ID_ERROR"
    "IS_EXISTS_ELEMENT_NAME_ERROR" = "IS_EXISTS_ELEMENT_NAME_ERROR"
    "IS_EXISTS_ELEMENT_TAGNAME_ERROR" = "IS_EXISTS_ELEMENT_TAGNAME_ERROR"
    "WAIT_FOR_ELEMENT_VISIBLE_ERROR" = "WAIT_FOR_ELEMENT_VISIBLE_ERROR"
    "WAIT_FOR_ELEMENT_CLICKABLE_ERROR" = "WAIT_FOR_ELEMENT_CLICKABLE_ERROR"
    "WAIT_FOR_CONDITION_ERROR" = "WAIT_FOR_CONDITION_ERROR"
    
    # 要素操作関連エラー (1051-1070) - 変更なし
    "GET_ELEMENT_TEXT_ERROR" = "GET_ELEMENT_TEXT_ERROR"
    "SET_ELEMENT_TEXT_ERROR" = "SET_ELEMENT_TEXT_ERROR"
    "CLEAR_ELEMENT_ERROR" = "CLEAR_ELEMENT_ERROR"
    "CLICK_ELEMENT_ERROR" = "CLICK_ELEMENT_ERROR"
    "DOUBLE_CLICK_ERROR" = "DOUBLE_CLICK_ERROR"
    "RIGHT_CLICK_ERROR" = "RIGHT_CLICK_ERROR"
    "MOUSE_HOVER_ERROR" = "MOUSE_HOVER_ERROR"
    "SEND_KEYS_ERROR" = "SEND_KEYS_ERROR"
    "SEND_SPECIAL_KEY_ERROR" = "SEND_SPECIAL_KEY_ERROR"
    "GET_ELEMENT_ATTRIBUTE_ERROR" = "GET_ELEMENT_ATTRIBUTE_ERROR"
    "SET_ELEMENT_ATTRIBUTE_ERROR" = "SET_ELEMENT_ATTRIBUTE_ERROR"
    "GET_ELEMENT_CSS_PROPERTY_ERROR" = "GET_ELEMENT_CSS_PROPERTY_ERROR"
    "SET_ELEMENT_CSS_PROPERTY_ERROR" = "SET_ELEMENT_CSS_PROPERTY_ERROR"
    "GET_HREF_ERROR" = "GET_HREF_ERROR"
    "SELECT_OPTION_BY_INDEX_ERROR" = "SELECT_OPTION_BY_INDEX_ERROR"
    "SELECT_OPTION_BY_TEXT_ERROR" = "SELECT_OPTION_BY_TEXT_ERROR"
    "DESELECT_ALL_OPTIONS_ERROR" = "DESELECT_ALL_OPTIONS_ERROR"
    "SET_CHECKBOX_ERROR" = "SET_CHECKBOX_ERROR"
    "SELECT_RADIO_BUTTON_ERROR" = "SELECT_RADIO_BUTTON_ERROR"
    "UPLOAD_FILE_ERROR" = "UPLOAD_FILE_ERROR"
    
    # ウィンドウ・タブ操作関連エラー (1071-1080) - 変更なし
    "RESIZE_WINDOW_ERROR" = "RESIZE_WINDOW_ERROR"
    "NORMAL_WINDOW_ERROR" = "NORMAL_WINDOW_ERROR"
    "MAXIMIZE_WINDOW_ERROR" = "MAXIMIZE_WINDOW_ERROR"
    "MINIMIZE_WINDOW_ERROR" = "MINIMIZE_WINDOW_ERROR"
    "FULLSCREEN_WINDOW_ERROR" = "FULLSCREEN_WINDOW_ERROR"
    "MOVE_WINDOW_ERROR" = "MOVE_WINDOW_ERROR"
    "CLOSE_WINDOW_ERROR" = "CLOSE_WINDOW_ERROR"
    "GET_WINDOW_HANDLE_ERROR" = "GET_WINDOW_HANDLE_ERROR"
    "GET_WINDOW_HANDLES_ERROR" = "GET_WINDOW_HANDLES_ERROR"
    "GET_WINDOW_SIZE_ERROR" = "GET_WINDOW_SIZE_ERROR"
    "DISCOVER_TARGETS_ERROR" = "DISCOVER_TARGETS_ERROR"
    "GET_AVAILABLE_TABS_ERROR" = "GET_AVAILABLE_TABS_ERROR"
    "SET_ACTIVE_TAB_ERROR" = "SET_ACTIVE_TAB_ERROR"
    "CLOSE_TAB_ERROR" = "CLOSE_TAB_ERROR"
    "ENABLE_PAGE_EVENTS_ERROR" = "ENABLE_PAGE_EVENTS_ERROR"
    
    # 情報取得関連エラー (1091-1100) - 変更なし
    "GET_URL_ERROR" = "GET_URL_ERROR"
    "GET_TITLE_ERROR" = "GET_TITLE_ERROR"
    "GET_SOURCE_CODE_ERROR" = "GET_SOURCE_CODE_ERROR"
    
    # スクリーンショット関連エラー (1101-1110) - 変更なし
    "SCREENSHOT_ERROR" = "SCREENSHOT_ERROR"
    "SCREENSHOT_OBJECT_ERROR" = "SCREENSHOT_OBJECT_ERROR"
    "SCREENSHOT_OBJECTS_ERROR" = "SCREENSHOT_OBJECTS_ERROR"
    
    # JavaScript実行関連エラー (1111-1120) - 変更なし
    "EXECUTE_SCRIPT_ERROR" = "EXECUTE_SCRIPT_ERROR"
    "EXECUTE_SCRIPT_ASYNC_ERROR" = "EXECUTE_SCRIPT_ASYNC_ERROR"
    
    # ストレージ操作関連エラー (1121-1130) - 変更なし
    "GET_COOKIE_ERROR" = "GET_COOKIE_ERROR"
    "SET_COOKIE_ERROR" = "SET_COOKIE_ERROR"
    "DELETE_COOKIE_ERROR" = "DELETE_COOKIE_ERROR"
    "CLEAR_ALL_COOKIES_ERROR" = "CLEAR_ALL_COOKIES_ERROR"
    "GET_LOCAL_STORAGE_ERROR" = "GET_LOCAL_STORAGE_ERROR"
    "SET_LOCAL_STORAGE_ERROR" = "SET_LOCAL_STORAGE_ERROR"
    "REMOVE_LOCAL_STORAGE_ERROR" = "REMOVE_LOCAL_STORAGE_ERROR"
    "CLEAR_LOCAL_STORAGE_ERROR" = "CLEAR_LOCAL_STORAGE_ERROR"
}

# ファイルを読み込み
$content = Get-Content $webDriverFile -Raw -Encoding UTF8

# エラーコード参照を更新
$updatedContent = $content
foreach ($oldCode in $errorCodeMapping.Keys) {
    $newCode = $errorCodeMapping[$oldCode]
    if ($oldCode -ne $newCode) {
        $pattern = "\$WebDriverErrorCodes\.$oldCode"
        $replacement = "\$WebDriverErrorCodes\.$newCode"
        $updatedContent = $updatedContent -replace $pattern, $replacement
        Write-Host "更新: $oldCode → $newCode" -ForegroundColor Yellow
    }
}

# ファイルに書き戻し
Set-Content -Path $webDriverFile -Value $updatedContent -Encoding UTF8

Write-Host "`n=== WebDriverエラーコード更新完了 ===" -ForegroundColor Green
Write-Host "ファイル: $webDriverFile" -ForegroundColor Cyan
